toggle_invitees:
  type: enum
  choices:
    - "Disabled"
    - "Show on Hover"
    - "Always Show"
  default: "Show on Hover"
  description:
    en: "Select if/how invitees will appear in the layout."
max_events:
  type: integer
  default: 3
  min: 1
  max: 50
  description:
    en: "Set the maximum number of events to appear in the layout. Consider adjusting this value to lower if facing performance issues."
highlight_today:
  type: bool
  default: true
  description:
    en: "Highlight events occuring on the same today"
style:
  type: enum
  choices:
    - "Default"
    - "Comfortable"
    - "Compact"
  default: "Default"
  description:
    en: "Select the layout's view style"
theme:
  type: enum
  choices:
    - "Default"
    - "Modern"
    - "Minimal"
    - "Detached"
    - "Colorful"
    - "Unicorn"
  default: "Default"
  description:
    en: "Select the layout's theme style"
